name: Setup Rust and Cargo cache
description: Installs Rust toolchain and configures Cargo cache.
inputs:
  components:
    description: "Optional comma-separated rustup components (for example: rustfmt, clippy)."
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Set up Rust (with components)
      if: ${{ inputs.components != '' }}
      uses: dtolnay/rust-toolchain@stable
      with:
        components: ${{ inputs.components }}

    - name: Set up Rust
      if: ${{ inputs.components == '' }}
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
