name: butterfly-bot
base: core24
version: '0.1.0'
summary: Always-on personal-ops AI assistant
license: MIT
description: |
  Butterfly Bot is a local-first AI assistant with daemon, CLI, and desktop UI,
  including bundled WASM tool modules for sandboxed tool execution.

grade: devel
confinement: strict

apps:
  butterfly-bot:
    command: snap/local/run-butterfly-bot
    extensions: [gnome]
    plugs:
      - network
      - network-bind
      - home
      - opengl
      - audio-playback

  butterfly-bot-ui:
    command: snap/local/run-butterfly-bot-ui
    extensions: [gnome]
    plugs:
      - network
      - network-bind
      - home
      - opengl
      - audio-playback

  butterfly-botd:
    command: snap/local/run-butterfly-botd
    daemon: simple
    install-mode: disable
    restart-condition: on-failure
    plugs:
      - network
      - network-bind
      - home

parts:
  butterfly-bot:
    plugin: rust
    source: .
    build-packages:
      - pkg-config
      - libssl-dev
      - libclang-dev
      - protobuf-compiler
      - libgtk-3-dev
      - libwebkit2gtk-4.1-dev
      - libayatana-appindicator3-dev
      - libsecret-1-dev
      - libnotify-dev
    stage-packages:
      - ca-certificates
      - openssl
      - libgtk-3-0
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
      - libsecret-1-0
      - libnotify4
      - libxkbcommon0
      - libasound2t64
    override-build: |
      set -eux
      craftctl default

      install -Dm755 target/release/butterfly-bot "$CRAFT_PART_INSTALL/usr/bin/butterfly-bot"
      install -Dm755 target/release/butterfly-botd "$CRAFT_PART_INSTALL/usr/bin/butterfly-botd"
      install -Dm755 target/release/butterfly-bot-ui "$CRAFT_PART_INSTALL/usr/bin/butterfly-bot-ui"

      chmod +x scripts/build_wasm_tools.sh
      ./scripts/build_wasm_tools.sh

      mkdir -p "$CRAFT_PART_INSTALL/usr/share/butterfly-bot/wasm"
      cp wasm/*_tool.wasm "$CRAFT_PART_INSTALL/usr/share/butterfly-bot/wasm/"

  snap-local:
    plugin: dump
    source: snap/local
    override-build: |
      set -eux
      craftctl default
      chmod +x "$CRAFT_PART_INSTALL"/snap/local/*
    organize:
      '*': snap/local/
