name: Release macOS App

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-upload-macos-app:
    name: Build and upload macOS app zip
    runs-on: macos-latest
    env:
      BUILD_KEYCHAIN: build.keychain-db
      APPLE_CERTIFICATE_BASE64: ${{ secrets['APPLE_CERTIFICATE_BASE64'] }}
      APPLE_CERTIFICATE_PASSWORD: ${{ secrets['APPLE_CERTIFICATE_PASSWORD'] }}
      APPLE_KEYCHAIN_PASSWORD: ${{ secrets['APPLE_KEYCHAIN_PASSWORD'] }}
      APPLE_SIGN_IDENTITY: ${{ secrets['APPLE_SIGN_IDENTITY'] }}
      APPLE_ID: ${{ secrets['APPLE_ID'] }}
      APPLE_TEAM_ID: ${{ secrets['APPLE_TEAM_ID'] }}
      APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets['APPLE_APP_SPECIFIC_PASSWORD'] }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo directories
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-macos-app-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Dioxus CLI
        run: cargo install dioxus-cli --locked

      - name: Import Apple signing certificate
        if: env.APPLE_CERTIFICATE_BASE64 != '' && env.APPLE_CERTIFICATE_PASSWORD != '' && env.APPLE_KEYCHAIN_PASSWORD != ''
        run: |
          set -euo pipefail
          CERT_PATH="$RUNNER_TEMP/apple-signing-cert.p12"
          echo "$APPLE_CERTIFICATE_BASE64" | base64 --decode > "$CERT_PATH"

          security create-keychain -p "$APPLE_KEYCHAIN_PASSWORD" "$BUILD_KEYCHAIN"
          security set-keychain-settings -lut 21600 "$BUILD_KEYCHAIN"
          security unlock-keychain -p "$APPLE_KEYCHAIN_PASSWORD" "$BUILD_KEYCHAIN"
          security import "$CERT_PATH" -k "$BUILD_KEYCHAIN" -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign -T /usr/bin/security
          security set-key-partition-list -S apple-tool:,apple: -k "$APPLE_KEYCHAIN_PASSWORD" "$BUILD_KEYCHAIN"

          EXISTING_KEYCHAINS="$(security list-keychains -d user | tr -d '"')"
          security list-keychains -d user -s "$BUILD_KEYCHAIN" $EXISTING_KEYCHAINS
          security default-keychain -d user -s "$BUILD_KEYCHAIN"

          echo "Available signing identities:"
          security find-identity -v -p codesigning "$BUILD_KEYCHAIN"

      - name: Build macOS app bundle
        run: |
          set -euo pipefail
          ./scripts/build-macos-app.sh

      - name: Locate generated .app and .app.zip
        id: app_artifacts
        run: |
          set -euo pipefail
          APP_ZIP="$(find "$GITHUB_WORKSPACE/dist" -type f -name '*.app.zip' -print0 | xargs -0 ls -t | head -n1 || true)"
          if [[ -z "$APP_ZIP" ]]; then
            echo "No .app.zip file found in dist" >&2
            exit 1
          fi

          APP_PATH="${APP_ZIP%.zip}"
          if [[ ! -d "$APP_PATH" ]]; then
            APP_PATH="$(find "$GITHUB_WORKSPACE/dist" -type d -name '*.app' -print0 | xargs -0 ls -td | head -n1 || true)"
          fi

          if [[ -z "$APP_PATH" || ! -d "$APP_PATH" ]]; then
            echo "No .app bundle found in dist" >&2
            exit 1
          fi

          echo "zip=$APP_ZIP" >> "$GITHUB_OUTPUT"
          echo "app=$APP_PATH" >> "$GITHUB_OUTPUT"
          echo "Found .app: $APP_PATH"
          echo "Found .app.zip: $APP_ZIP"

      - name: Notarize and staple app
        if: env.APPLE_ID != '' && env.APPLE_TEAM_ID != '' && env.APPLE_APP_SPECIFIC_PASSWORD != ''
        env:
          APP_PATH: ${{ steps.app_artifacts.outputs.app }}
          APP_ZIP: ${{ steps.app_artifacts.outputs.zip }}
        run: |
          set -euo pipefail
          echo "Submitting app zip for notarization..."
          xcrun notarytool submit "$APP_ZIP" \
            --apple-id "$APPLE_ID" \
            --team-id "$APPLE_TEAM_ID" \
            --password "$APPLE_APP_SPECIFIC_PASSWORD" \
            --wait

          echo "Stapling ticket to app bundle..."
          xcrun stapler staple -v "$APP_PATH"
          xcrun stapler validate -v "$APP_PATH"

          echo "Rebuilding zip after stapling..."
          rm -f "$APP_ZIP"
          ditto -c -k --sequesterRsrc --keepParent "$APP_PATH" "$APP_ZIP"

          echo "Final signature verification..."
          codesign --verify --deep --strict --verbose=2 "$APP_PATH"
          spctl -a -vvv -t exec "$APP_PATH"

      - name: Skip notarization notice
        if: env.APPLE_ID == '' || env.APPLE_TEAM_ID == '' || env.APPLE_APP_SPECIFIC_PASSWORD == ''
        run: |
          echo "Notarization secrets not configured; publishing non-notarized macOS app artifact."
          echo "Users may need to use Open Anyway or clear quarantine after download."

      - name: Locate generated .app.zip
        id: appzip
        run: |
          set -euo pipefail
          APP_ZIP="${{ steps.app_artifacts.outputs.zip }}"
          if [[ -z "$APP_ZIP" ]]; then
            echo "No .app.zip file found in dist" >&2
            exit 1
          fi
          echo "file=$APP_ZIP" >> "$GITHUB_OUTPUT"
          echo "Found .app.zip: $APP_ZIP"

      - name: Cleanup signing keychain
        if: always() && env.APPLE_CERTIFICATE_BASE64 != '' && env.APPLE_CERTIFICATE_PASSWORD != '' && env.APPLE_KEYCHAIN_PASSWORD != ''
        run: |
          set -euo pipefail
          security delete-keychain "$BUILD_KEYCHAIN" || true

      - name: Upload .app.zip to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.appzip.outputs.file }}
          fail_on_unmatched_files: true
