name: Release Debian Package

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-upload-deb:
    name: Build and upload .deb
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux build dependencies
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y \
            python3 \
            python3-pil \
            pkg-config \
            libssl-dev \
            libclang-dev \
            protobuf-compiler \
            libprotobuf-dev \
            libsecret-1-dev \
            libnotify-dev \
            patchelf \
            fakeroot \
            dpkg-dev

      - name: Cache cargo directories
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-deb-${{ hashFiles('**/Cargo.lock') }}

      - name: Bundle preflight
        run: test -f assets/icon.png

      - name: Build Debian package
        run: |
          set -euo pipefail
          if ! ./scripts/build-deb.sh; then
            echo "==== Debug: dist tree ===="
            find dist -maxdepth 6 -print 2>/dev/null || true
            echo "==== Debug: target/release tree ===="
            find target/release -maxdepth 4 -print 2>/dev/null || true
            exit 1
          fi

      - name: Locate generated .deb
        id: deb
        run: |
          set -euo pipefail
          DEB_FILE="$(find "$GITHUB_WORKSPACE" -type f -name '*.deb' \
            \( -path '*/dist/*' -o -path '*/target/*' \) \
            -printf '%T@ %p\n' | sort -nr | head -n1 | cut -d' ' -f2-)"
          if [[ -z "$DEB_FILE" ]]; then
            echo "No .deb file found" >&2
            exit 1
          fi
          echo "file=$DEB_FILE" >> "$GITHUB_OUTPUT"
          echo "Found .deb: $DEB_FILE"

      - name: Upload .deb to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.deb.outputs.file }}
          fail_on_unmatched_files: true