name: Install Ubuntu build dependencies
description: Installs native Ubuntu packages required to build and test Butterfly Bot.
runs:
  using: composite
  steps:
    - name: Install apt packages
      shell: bash
      run: |
        set -euo pipefail

        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          build-essential \
          pkg-config \
          cmake \
          clang \
          protobuf-compiler \
          libprotobuf-dev \
          libclang-dev \
          libssl-dev \
          libgtk-3-dev \
          libayatana-appindicator3-dev \
          libsecret-1-dev \
          libnotify-dev \
          libdbus-1-dev \
          libxdo-dev \
          libasound2-dev

        if apt-cache show libwebkit2gtk-4.1-dev >/dev/null 2>&1; then
          sudo apt-get install -y --no-install-recommends libwebkit2gtk-4.1-dev
        else
          sudo apt-get install -y --no-install-recommends libwebkit2gtk-4.0-dev
        fi

    - name: Export protoc env
      shell: bash
      run: |
        set -euo pipefail

        echo "PROTOC=$(command -v protoc)" >> "$GITHUB_ENV"

        if [ -d /usr/include/google/protobuf ]; then
          echo "PROTOC_INCLUDE=/usr/include" >> "$GITHUB_ENV"
        elif [ -d /usr/local/include/google/protobuf ]; then
          echo "PROTOC_INCLUDE=/usr/local/include" >> "$GITHUB_ENV"
        fi
